### ISSUE TITLE
окай я пашол ацуда

### ISSUE THREAD

**Issue by handicraftsman** [IgorTimofeev/JFXOCEmulator#1]

**Comment by handicraftsman** [comment]
А так, вполне хорошая идея - написать сабж на java.

**Comment by IgorTimofeev** [comment]
![2018-10-11 20 18 25](https://user-images.githubusercontent.com/11760002/46834564-68bfae80-cdb4-11e8-932a-aaec73fc9f17.png)

**Comment by handicraftsman** [comment]
О хоспаде
